vim.pack.add({
  'https://github.com/nvim-treesitter/nvim-treesitter',
  'https://github.com/nvim-mini/mini.nvim',
  'https://github.com/MeanderingProgrammer/render-markdown.nvim',
})
require('render-markdown').setup({})
vim.pack.add({
  'https://github.com/tadmccorkle/markdown.nvim'
})
require('markdown').setup()
